/* Generated By:JavaCC: Do not edit this line. JavascriptTreeConstants.java Version 7.0.5 */
package javascriptInterpreter.tree;

import javascriptInterpreter.parser.*;

public interface JavascriptTreeConstants
{
  public int JJTPRIMARYEXPRESSION = 0;
  public int JJTLITERAL = 1;
  public int JJTARRAYLITERAL = 2;
  public int JJTELLISION = 3;
  public int JJTELEMENTLIST = 4;
  public int JJTARRAYELEMENT = 5;
  public int JJTSPREADELEMENT = 6;
  public int JJTOBJECTLITERAL = 7;
  public int JJTVOID = 8;
  public int JJTPROPERTYDEFINITION = 9;
  public int JJTFUNCTIONEXPRESSION = 10;
  public int JJTPARENTHESIZEDEXPRESSION = 11;
  public int JJTLEFTSIDEEXPRESSION = 12;
  public int JJTCALLEXPRESSION = 13;
  public int JJTARGUMENTS = 14;
  public int JJTNEWEXPRESSION = 15;
  public int JJTMEMBEREXPRESSION = 16;
  public int JJTUPDATEEXPRESSION = 17;
  public int JJTUNARYEXPRESSION = 18;
  public int JJTEXPONENTIATIONEXPRESSION = 19;
  public int JJTMULTIPLICATIVEEXPRESSION = 20;
  public int JJTADDITIVEEXPRESSION = 21;
  public int JJTSHIFTEXPRESSION = 22;
  public int JJTRELATIONALEXPRESSION = 23;
  public int JJTEQUALITYEXPRESSION = 24;
  public int JJTBITWISEANDEXPRESSION = 25;
  public int JJTBITWISEXOREXPRESSION = 26;
  public int JJTBITWISEOREXPRESSION = 27;
  public int JJTLOGICALANDEXPRESSION = 28;
  public int JJTLOGICALOREXPRESSION = 29;
  public int JJTCONDITIONALEXPRESSION = 30;
  public int JJTASSIGNMENTEXPRESSION = 31;
  public int JJTEXPRESSION = 32;
  public int JJTSTATEMENT = 33;
  public int JJTEMPTYSTATEMENT = 34;
  public int JJTEXPRESSIONSTATEMENT = 35;
  public int JJTVARIABLEDEFINITION = 36;
  public int JJTVARIABLEDECLARATIONLIST = 37;
  public int JJTVARIABLEDECLARATION = 38;
  public int JJTBLOCK = 39;
  public int JJTLABELEDSTATEMENT = 40;
  public int JJTIFSTATEMENT = 41;
  public int JJTSWITCHSTATEMENT = 42;
  public int JJTCASEBLOCK = 43;
  public int JJTCASECLAUSES = 44;
  public int JJTCASECLAUSE = 45;
  public int JJTDEFAULTCLAUSE = 46;
  public int JJTDOSTATEMENT = 47;
  public int JJTWHILESTATEMENT = 48;
  public int JJTFORSTATEMENT = 49;
  public int JJTFORHEADER = 50;
  public int JJTFORINITIALIZER = 51;
  public int JJTFORINHEADER = 52;
  public int JJTFORINBINDING = 53;
  public int JJTCONTINUESTATEMENT = 54;
  public int JJTBREAKSTATEMENT = 55;
  public int JJTRETURNSTATEMENT = 56;
  public int JJTTHROWSTATEMENT = 57;
  public int JJTTRYSTATEMENT = 58;
  public int JJTCATCHCLAUSES = 59;
  public int JJTCATCHCLAUSE = 60;
  public int JJTFINALLYCLAUSE = 61;
  public int JJTNAMEDFUNCTION = 62;
  public int JJTANONYMOUSFUNCTION = 63;
  public int JJTFORMALPARAMETERS = 64;
  public int JJTFUNCTIONBODY = 65;
  public int JJTTOPSTATEMENT = 66;
  public int JJTTOPSTATEMENTS = 67;
  public int JJTPROGRAM = 68;


  public String[] jjtNodeName = {
    "primaryExpression",
    "literal",
    "arrayLiteral",
    "ellision",
    "elementList",
    "arrayElement",
    "spreadElement",
    "objectLiteral",
    "void",
    "propertyDefinition",
    "functionExpression",
    "parenthesizedExpression",
    "leftSideExpression",
    "callExpression",
    "arguments",
    "newExpression",
    "memberExpression",
    "updateExpression",
    "unaryExpression",
    "exponentiationExpression",
    "multiplicativeExpression",
    "additiveExpression",
    "shiftExpression",
    "relationalExpression",
    "equalityExpression",
    "bitwiseAndExpression",
    "bitwiseXorExpression",
    "bitwiseOrExpression",
    "logicalAndExpression",
    "logicalOrExpression",
    "conditionalExpression",
    "assignmentExpression",
    "expression",
    "statement",
    "emptyStatement",
    "expressionStatement",
    "variableDefinition",
    "variableDeclarationList",
    "variableDeclaration",
    "block",
    "labeledStatement",
    "ifStatement",
    "switchStatement",
    "caseBlock",
    "caseClauses",
    "caseClause",
    "defaultClause",
    "doStatement",
    "whileStatement",
    "forStatement",
    "forHeader",
    "forInitializer",
    "forInHeader",
    "forInBinding",
    "continueStatement",
    "breakStatement",
    "returnStatement",
    "throwStatement",
    "tryStatement",
    "catchClauses",
    "catchClause",
    "finallyClause",
    "namedFunction",
    "anonymousFunction",
    "formalParameters",
    "functionBody",
    "topStatement",
    "topStatements",
    "program",
  };
}
/* JavaCC - OriginalChecksum=254378d02841c8425c9b65f76e5cf250 (do not edit this line) */
